enum ActionTypes {
  ALERT_COLOR = 'ALERT_COLOR',
  ALERT_MESSAGE = 'ALERT_MESSAGE',
  AUTHENTICATED = 'AUTHENTICATED',
  CURRENT_USER = 'CURRENT_USER',
  RESET_STORE = 'RESET_STORE',
}

export default ActionTypes;
